### ISSUE TITLE
师傅不支持自己添加指纹特征吗？

### ISSUE THREAD

**Issue by helloyw** [P001water/P1finger#2]
师傅不支持自己添加指纹特征吗？

**Comment by P001water** [comment]
因为现在不开源，指纹库的规则我自己设计改动的，指纹不通用

**Comment by notalkingya** [comment]
师傅现在又多少条指纹了呢

> 因为现在不开源，指纹库的规则我自己设计改动的，指纹不通用

**Comment by P001water** [comment]
不用太注意指纹数量，误报漏报issue提上来很快就能加上，现有的应该也足够了
