### ISSUE TITLE
结果输出

### ISSUE THREAD

**Issue by clearly3** [P001water/P1finger#4]
![image](https://github.com/user-attachments/assets/043f2d67-c6be-4c7e-9b0b-6ef98361b38d)
建议将识别结果整合输出

**Comment by P001water** [comment]
这个是单个测试的时候方便查看每种指纹的命中的，批量的时候是整合输出的

![image](https://github.com/user-attachments/assets/d26bd055-12f9-472a-9b49-1a33f5eb047d)
